const goats = [
  {
    id: 'goat1',
    name: 'billy',
    disposition: 'rude',
    imageUrl: 'https://ichef.bbci.co.uk/news/624/cpsprodpb/C271/production/_98677794_gettyimages-486869012.jpg',
    fullness: 67,
    favPose: 'downward facing dog',
    isFainting: true,
    color: 'brown',
  },
  {
    id: 'goat2',
    name: 'Ted',
    disposition: 'sloppy',
    imageUrl: 'https://images.all-free-download.com/images/graphiclarge/goat_animal_horns_219095.jpg',
    fullness: 99,
    favPose: 'beg',
    isFainting: true,
    color: 'white',
  },
  {
    id: 'goat3',
    name: 'Lucy',
    disposition: 'grumpy',
    imageUrl: 'https://cdn.pixabay.com/photo/2018/09/18/19/59/goat-3687106__340.jpg',
    fullness: 25,
    favPose: 'charging',
    isFainting: false,
    color: 'black',
  },
  {
    id: 'goat4',
    name: 'Bob',
    disposition: 'apathetic',
    imageUrl: 'https://www.brighthope.org/wp-content/uploads/2018/09/goat.jpg',
    fullness: 50,
    favPose: 'neutral pose',
    isFainting: true,
    color: 'tan',
  },
  {
    id: 'goat5',
    name: 'billy',
    disposition: 'gifted',
    imageUrl: 'http://thelibertarianrepublic.com/wp-content/uploads/2015/05/sexy-goat.jpg',
    fullness: 100,
    favPose: 'staring',
    isFainting: true,
    color: 'brown',
  },
];

export default { goats };
